version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Use an environment variable for the API key
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATA_PATH=/data
    volumes:
      - ./data:/data # Maps host's ./data directory to container's /data directory
    container_name: LLM_Flaky_Finder
